### ISSUE TITLE
Fail to download the data

### ISSUE THREAD

**Issue by gatsby2016** [paip-2019/challenge#18]
Hi, i am downloading the zip file data.
However, i can't download the zip file because of the slowwww network. It shows that only about 10kb/s when i attempt to download it. And eventually, the zip file downloading failed. 
Even, I tried different browsers such as Firefox / Chrome .. Failed due to the slow network.  

Until now, no one was downloaded. 

But i am very sure that my network was not the problem. So, i wonder if there are other ways to download the data and solve this problem.

Thanks.

**Comment by wisepaip** [comment]
Hello, could you give us more information to inspect the issue?
1. Network Speed; Could you give us the error message when it has occurred? 
2. Firewall: Do you happen to download the file in China? There is a possibility that firewall blocks AWS which we're using for the system.

**Comment by gatsby2016** [comment]
![1](https://user-images.githubusercontent.com/24687913/56410872-536e9400-62b1-11e9-8eb3-d4d525da2ff6.png)

![2](https://user-images.githubusercontent.com/24687913/56410875-57021b00-62b1-11e9-9d54-9ca6cc6b494d.png)

Like this. 
Yes. I am in China. AT begining, only about 10kb/s; after a while, turn to 0kb/s; and finally, it turns to **Network Error**, and failed..

maybe i should try some other ways ...   :<

**Comment by wisepaip** [comment]
We doubt that it won't firewall issue because we haven't been reported from other participants in China.
Let us know if the download keeps failing.

**Comment by gatsby2016** [comment]
Thank you.  I solved this problem. (need to start global mode when open proxy)
