### ISSUE TITLE
Basic Python scripts for loading and visualizing the data.

### ISSUE THREAD

**Issue by JunMa11** [paip-2019/challenge#20]
Dear PAIP organizers,

Thanks for organizing the great challenge.

Would it be possible for you to provide some basic Python/Matlab scripts for loading and visualizing the data? 
e.g. [MICCAI 2019 KITS Challenge](https://github.com/neheller/kits19)

**Comment by wisepaip** [comment]
Hello,
Thank you for the suggestion. 
We need to discuss the issue with our team about providing the scripts. 
We will let you know soon through here.

**Comment by hjoonjang** [comment]
@JunMa11 
I've released a sample code, 'utils.py' in this repo, so you can read it and try visualizing with the given mask data.

Unfortunately, the sample code does not (yet) include the svs-loading part, which is supported by well-known open sourced libraries (e.g. [openslide](https://openslide.org/), [pyvips](https://libvips.github.io/pyvips/), etc.). We will discuss whether it should be provided or not. Anyway, I guess you may also like to see [here](https://camelyon17.grand-challenge.org/Data/).
