### ISSUE TITLE
Can not open  Image masks 

### ISSUE THREAD

**Issue by yangsenwxy** [paip-2019/challenge#21]
Dear PAIP organizers,

       Thanks for organizing the great challenge.
       The image masks can not open . I want to know how to open it ?  The openslide can not open it .

**Comment by yangsenwxy** [comment]
I have solved it.

**Comment by zhaoshuaibit** [comment]
> I have solved it.

May I know which tool did you use to open the '.tif' format mask image? Thank you

**Comment by wisepaip** [comment]
The PAIP 2019's  Binay masks are distributed in **LZW** compression format. 

The easiest way to open the TIF files is by using the **[Fiji viewer.](https://fiji.sc/)**

If you want to open the binary mask from other image viewers, we recommend processing for resizing the images by codes.

 

### Resize and Save Images

  Import the basic image processing library, [scikit-image](https://scikit-image.org/docs/dev/install.html)
` >>> import skimage.io as io  
`

You could load the images with the default setting.  It will automatically uncompressed.
`  >>> img = io.imread("<load_filename.tif>") `

You could save the images as large uncompressed TIF file format with the default setting with this code.
` >>> io.imsave("<save_filename.tif>", img)   `

**Comment by hjoonjang** [comment]
> The PAIP 2019's Binay masks are distributed in **LZW** compression format.
> 
> The easiest way to open the TIF files is by using the **[Fiji viewer.](https://fiji.sc/)**
> 
> If you want to open the binary mask from other image viewers, we recommend processing for resizing the images by Python codes.
> 
> ### Resize and Save Images
> Import the basic image processing library, [scikit-image](https://scikit-image.org/docs/dev/install.html)
> `>>> import skimage.io as io `
> 
> You could load the images with the default setting. It will automatically uncompressed.
> ` >>> img = io.imread("<load_filename.tif>")`
> 
> You could save the images as large uncompressed TIF file format with the default setting with this code.
> `>>> io.imsave("<save_filename.tif>", img) `

Additionally, regardless of whether it is decompressed or not, you may not be able to open it with 'simple' image viewers (e.g. Windows' default, Fiji, etc.) when it has more data element (i.e. width*height*channel) than max(int32) = 2^31 = 2,147,483,647, in my experience.

On the other hand, utilizing skimage package has never let me down even with simple loading & saving code once you have enough memory size. So I recommend you to process images at the code level into several partial blocks of the image (or something else) if you would like to handle it with the simple image viewers.

**Comment by yangsenwxy** [comment]
Thank you.

**Comment by harishprabhala** [comment]
> The PAIP 2019's Binay masks are distributed in **LZW** compression format.
> 
> The easiest way to open the TIF files is by using the **[Fiji viewer.](https://fiji.sc/)**
> 
> If you want to open the binary mask from other image viewers, we recommend processing for resizing the images by Python codes.
> 
> ### Resize and Save Images
> Import the basic image processing library, [scikit-image](https://scikit-image.org/docs/dev/install.html)
> `>>> import skimage.io as io `
> 
> You could load the images with the default setting. It will automatically uncompressed.
> ` >>> img = io.imread("<load_filename.tif>")`
> 
> You could save the images as large uncompressed TIF file format with the default setting with this code.
> `>>> io.imsave("<save_filename.tif>", img)`

This method is creating about 2GB sized binary masks. These masks are much larger than the original svs files. Anyway we can compress them to the size of the main svs image? Because these images are way too large for just binary masks.

**Comment by hjoonjang** [comment]
@harishprabhala 
I apologize for missing your comment.
About the compression, there are many algorithms such as png, gif, jpeg, etc., which are distinguishable by their losslessness or spatial efficiency. Basically, the given (compressed) SVS format is utilizing the JPEG2000 algorithm already (lossy compression). That means you can freely take either way of re-compressing or leave it as a raw array once decompressing the WSIs. I would like to recommend you to use raw information because JPEG leaves irreversible losses on the contents so that the losses can be accumulated over and over again whenever you try re-compressing the images.

When it comes to the binary **mask** images, however, please check our repo and see ```submission_compress.py```([link](https://github.com/paip-2019/challenge/blob/master/submission_compress.py)) but, again, it will not work as commonly expected for any arrays with continuous values such as probability maps.
