### ISSUE TITLE
The Task 1 problem 

### ISSUE THREAD

**Issue by yangsenwxy** [paip-2019/challenge#22]
Dear PAIP organizers,
        Task 1: Liver Cancer Segmentation. We should predict the  entire tumor area and viable tumor area? or viable tumor ?

**Comment by wisepaip** [comment]
Hi,

For **task 1,** you will be asked to **predict the entire tumor area**. 
As described in [dataset description, ](https://paip2019.grand-challenge.org/Dataset/) **the entire tumor area** means :

> the outermost boundary enclosing all dispersed viable tumor cell nests, tumor necrosis, and tumor capsule one file holds one whole tumor area

You could find the ground truth for task 1 as a TIF file with Whole Tumor Mask Image.

**Comment by wisepaip** [comment]
We're sorry for causing the confusion. I've deleted the previous comment.

For **task 1**, you will predict the **viable tumor cell.** 

> **Viable tumor area**: multiple closed regions or irregular ring-shaped region lined by **the Green line**: This region is defined as viable tumor cell nests and as precisely as possible, boundaries along the boundary between the cell and the surrounding stroma.

**Comment by yangsenwxy** [comment]
Thank you .For Task 2, We should predict the entire tumor and calculate ratio? or only calculate ratio?

**Comment by GHLee89** [comment]
Hi,
For Task 2, you should predict the ratio of viable tumor over the entire tumor.

**Comment by yangsenwxy** [comment]
Hi, 
   For task 2, the  result submit only   ratio of viable tumor over the entire tumor.Don't submit the contain the entire tumor segmentation image.Right?

**Comment by GHLee89** [comment]
For task 1, you need to submit the mask image of viable tumor area.
For task 2, you need to submit the ratio of viable tumor over the entire tumor.
So, you don't need to submit the entire tumor segmentation.
We will describe the way of submission on submit page after the release of validation data.

**Comment by yangsenwxy** [comment]
OK,very Thank you.
