### ISSUE TITLE
reading svs file

### ISSUE THREAD

**Issue by DecentMakeover** [paip-2019/challenge#26]
Could someone kindly post code to read an svs file?

Thanks in advance.

**Comment by PingjunChen** [comment]
Hi Ryan,
You may refer functions "load_wsi_head " and "load_wsi_level_img" in https://github.com/PingjunChen/pyslide/blob/master/pyslide/pyramid/_pyramid.py to load whole slide images. The python package openslide-python needs to be installed before use. The installation can refer to the "Installation" in README of [https://github.com/openslide/openslide-python](https://github.com/openslide/openslide-python).

**Comment by DecentMakeover** [comment]
@PingjunChen Thanks a lot.

Are you taking part too?
