### ISSUE TITLE
 The black solid line

### ISSUE THREAD

**Issue by YANRUI121** [paip-2019/challenge#27]
Dear PAIP organizers,

Can you help to explain what the black solid line in the images means?

I opened the image using Apeiro ImageScope v11.1.2.752.

![SHOT1](https://user-images.githubusercontent.com/18369266/58497582-d3d8bc80-81ae-11e9-8a05-89b755d10e9f.jpg)
![SHOT2](https://user-images.githubusercontent.com/18369266/58497583-d3d8bc80-81ae-11e9-91e3-1e9574ee7e86.jpg)

**Comment by wisepaip** [comment]
Hello,
The black line means the region is selected. When you click the annotation layer, it changes to the dark solid line. 

Reference : [Aperion User Guide, page 18](http://tmalab.jhmi.edu/aperiou/userguides/Image_Analysis_UG.pdf)

**Comment by YANRUI121** [comment]
> Hello,
> The black line means the region is selected. When you click the annotation layer, it changes to the dark solid line.
> 
> Reference : [Aperion User Guide, page 18](http://tmalab.jhmi.edu/aperiou/userguides/Image_Analysis_UG.pdf)

Yes, I see. Thank you very much.
