### ISSUE TITLE
Preprocessing codes for Liver Cancer Segmentation Challenge

### ISSUE THREAD

**Issue by PingjunChen** [paip-2019/challenge#32]
I wrote some codes for liver slide preprocessing in [LiverCancerSeg](https://github.com/PingjunChen/LiverCancerSeg.git). I think the codes may help those unfamiliar with whole slide image processing to start the challenge.

**Comment by DecentMakeover** [comment]
Hey Thanks a lot , this should really help

**Comment by maxsagitov** [comment]
Thank you! When will you post the next steps? It's my first DL practice )

**Comment by PingjunChen** [comment]
@maxsagitov Thanks for your interest, but the answer might disappoint you. Since this is a challenge, the next steps are my current planned methodology. I would instead choose to release these codes after the challenge is ended. But I believe the current code should be helpful to preprocess whole slide images.

**Comment by DecentMakeover** [comment]
Hi 

Can Whole slide images be converted to nii.gz format?

Thanks

**Comment by PingjunChen** [comment]
@DecentMakeover As far as I know, no vendors save the whole slide images using the nii.gz format, which is mainly used for MRI. The storage structure of the whole slide image and 3d/4d MRI image is very different.

**Comment by DecentMakeover** [comment]
Hmmm, okay ill look into it
