### ISSUE TITLE
Facing some problems using OpenSlide in Python

### ISSUE THREAD

**Issue by charleschen22** [paip-2019/challenge#33]
I am using OpenSlide to read in 'tif' image in Python, there is an issue occurring every time. 
My code is:
slide_paths = './data/ViableMask/01_01_0083_viable.tif'
img = openslide.open_slide(slide_path)
And I got the error:
OSError: cannot identify image file './data/ViableMask/01_01_0085_viable.tif'
But my tif file is indeed in the folder. And this function works well for '.svs' file.
Anyone know what is happening here? I will be really appreciated.

**Comment by PingjunChen** [comment]
@charleschen22 'tif' image is just a normal image, different from 'svs', which is a pyramidal image. You can just use `skimage`, `cv2` to open it.

**Comment by charleschen22** [comment]
> @charleschen22 'tif' image is just a normal image, different from 'svs', which is a pyramidal image. You can just use `skimage`, `cv2` to open it.

Thanks for your tips. 'skimages' and 'cv2' works for me. 
Just still confused about  'Openslides', according to its officatil documentation, it should work for images in 'tif' format and there are many examples online using 'open_slide' function to open 'tif' images.(https://openslide.org/api/python/). Don't know why it does not work for me.
Thanks for your advice again!

**Comment by PingjunChen** [comment]
@charleschen22 OpenSlide supports pyramidal tiff/tif files, those tiff/tif files are not normal tiff/tif files. Although they share the same file suffix, pyramidal tiff/tif files have a special `format` field in their file header. OpenSlide would first check the format is supported or not before opening the file. Normal tiff/tif files don't contain that special `format` in the header, therefore they cannot be opened by OpenSlide. Yet you can use `imagemagick` to convert normal tiff/tif files to pyramidal ones. I have written a python wrapper which you can refer to [create_pyramidal_img](https://github.com/PingjunChen/pyslide/blob/master/pyslide/pyramid/_pyramid.py).

**Comment by charleschen22** [comment]
> @charleschen22 OpenSlide supports pyramidal tiff/tif files, those tiff/tif files are not normal tiff/tif files. Although they share the same file suffix, pyramidal tiff/tif files have a special `format` field in their file header. OpenSlide would first check the format is supported or not before opening the file. Normal tiff/tif files don't contain that special `format` in the header, therefore they cannot be opened by OpenSlide. Yet you can use `imagemagick` to convert normal tiff/tif files to pyramidal ones. I have written a python wrapper which you can refer to [create_pyramidal_img](https://github.com/PingjunChen/pyslide/blob/master/pyslide/pyramid/_pyramid.py).

Now I get it. Really appreciated your time for answering my question and thanks for sharing your code! Thx.
