### ISSUE TITLE
Submission Failure

### ISSUE THREAD

**Issue by newhyun00** [paip-2019/challenge#34]
Dear PAIP organizer,

Thank you for your efforts in organizing the challenge

Tried my initial submission today but faced errors as below
---------------------------

Unfortunately the evaluation for the submission to PAIP2019 failed with an error. The error message is:

AssertionError

You may wish to try and correct this, or contact the challenge organizers. The following information may help them:
User: newhyun00
Job ID: d17437f5-e278-4992-ab1a-8282ff77f89a
Submission ID: c36142fb-9d0c-4de3-ab76-35085db73c15

-------------------------------

Tried three times but ran into the same problems 

Could you look into this issue?

Thank you,
Hyun

**Comment by wisepaip** [comment]
Hello @newhyun00 
It seems the image size does not fit. Could you check if your submitted images are corresponding to the original WSI's **level 0 dimension**?
`File "/opt/evaluation/evaluation.py", line 144, in memmap_jaccard assert(img1.shape == img2.shape) AssertionError`

If you keep failing on the submission, please send me an email (wisepaip@gmail.com). We will take a look at your submitted images.

Thank you.

**Comment by hjoonjang** [comment]
@newhyun00 
I guess it might be the case that the image shape was confused between (H, W) format and (W, H) format. Please check the shape of the images.

Thanks to your question, we will update our evaluation code to print the details of the assertion error. Hope it helps to debug.

As what @wisepaip mentioned above, if you keep stuck in troubles with submissions, please send an email with your submission file samples.

Thank you.

**Comment by newhyun00** [comment]
> Hello @newhyun00
> It seems the image size does not fit. Could you check if your submitted images are corresponding to the original WSI's **level 0 dimension**?
> `File "/opt/evaluation/evaluation.py", line 144, in memmap_jaccard assert(img1.shape == img2.shape) AssertionError`
> 
> If you keep failing on the submission, please send me an email ([wisepaip@gmail.com](mailto:wisepaip@gmail.com)). We will take a look at your submitted images.
> 
> Thank you.

Thank you for the prompt response

You are correct about the image size error
It seems there is an error in my code
I'll fix it and let you know if the submission error continues

**Comment by newhyun00** [comment]
> @newhyun00
> I guess it might be the case that the image shape was confused between (H, W) format and (W, H) format. Please check the shape of the images.
> 
> Thanks to your question, we will update our evaluation code to print the details of the assertion error. Hope it helps to debug.
> 
> As what @wisepaip mentioned above, if you keep stuck in troubles with submissions, please send an email with your submission file samples.
> 
> Thank you.

The image size error is correct
I'll update the code and let you know if the submission problem continues

Thank you
