### ISSUE TITLE
Issue regarding the shape of submitted file for task 1 

### ISSUE THREAD

**Issue by haranrk** [paip-2019/challenge#37]
<img width="615" alt="Screenshot 2019-08-20 at 9 37 59 AM" src="https://user-images.githubusercontent.com/19757243/63316952-8f346b80-c32e-11e9-93f7-56cb5efc85bc.png">
<img width="455" alt="Screenshot 2019-08-20 at 9 37 37 AM" src="https://user-images.githubusercontent.com/19757243/63316951-8f346b80-c32e-11e9-9ae3-e9dddec062fd.png">

The shape of my file seems to be consistent with the level '0' dimension of the slide image as reported by open slide. However, the system rejected my submission stating that the shape required is the transpose of the level '0' dimensions.

**Comment by hjoonjang** [comment]
Hi, @haranrk 
As far as I know, ```openslide``` shows dimensions in **WxH (X-Y)** manner, which is the opposite of the common ```numpy``` shape orders, **HxW (Y-X)**. So if you try to read the WSI dimensions with ```numpy.ndarray``` method, I think you will see what has been going on, though the reading procedure might be tricky. (FYI, ```pyvips``` library supports more straightforward usages to load WSIs.) Please check your output shape compared to the original dimensions.

Thank you,
Hyungjoon

**Comment by haranrk** [comment]
Yes, that makes sense. I was able to submit by transposing the image.
