### ISSUE TITLE
tif save problem

### ISSUE THREAD

**Issue by zxzhaoeric** [paip-2019/challenge#39]
Dear organizer,

When I save the results as tif files,
"imsave(submission_filename, img, compress=9)",
there comes an error that the data is too large for standard TIFF file.
I am sure that the dimension of my results is the same as the level 0 dimension.
How can I solve this problem?

Thanks

**Comment by hjoonjang** [comment]
Hi, @zxzhaoeric 
I've looked at the source code ([here](https://github.com/blink1073/tifffile/blob/master/tifffile/tifffile.py)), and I guess you can either set the image's dtype as ```np.uint8``` explicitly beforehand or give ```bigtiff=True``` kwargs explicitly.

If you still have the same problem after trying them, please let me know.
Thanks

**Comment by zxzhaoeric** [comment]
@hjoonjang 
Thanks so much. It works!
