### ISSUE TITLE
filling the holes in the tissue mask

### ISSUE THREAD

**Issue by bmarami** [paip-2019/challenge#40]
Could you please explain this step?
**"Filling in empty holes and removing small fractions of tissue smaller than 10 pixels in size (regarding them as noises) on the Tissue masks"**
More specifically, how do you fill empty holes? If you are dilating the image, what is the kernel size you are using for how many iterations?

**Comment by hjoonjang** [comment]
Hi, @bmarami 
There are well-known packages supporting 'removing holes' function.
We utilized [this](https://scikit-image.org/docs/dev/api/skimage.morphology.html#skimage.morphology.remove_small_holes) with ```area_threshold=10``` by the descriptions and ```connectivity=1``` as default.

Hope this helps.
Thanks

**Comment by bmarami** [comment]
Thank you for your quick response.
