### ISSUE TITLE
I can't access Data Use Agreement Website.

### ISSUE THREAD

**Issue by INFINITEEE** [paip-2019/challenge#46]
If I clicked the link of Data Use agreement, the website showed the page looks like that. 
Could you ckeck it for me?
![a](https://user-images.githubusercontent.com/43368107/64403004-d8681780-d0b1-11e9-965d-4b8cd8099d10.PNG)
![캡처](https://user-images.githubusercontent.com/43368107/64403010-daca7180-d0b1-11e9-8a73-5240e2113bb5.PNG)

**Comment by wisepaip** [comment]
Thanks for the feedback! 
We have resolved the issue by uploading the correct link. 
Please visit[ the submission page ](https://paip2019.grand-challenge.org/evaluation/submissions/create/)again. 
Thank you.
